/* @var className  $this /
<h1>slider2.phtml</h1>
<div>
    <?php echo 'Current Frontend Package: ' . Mage::getSingleton('core/design_package')->getPackageName() . '<br />' ?>
    <?php echo 'Current Frontend Theme: ' . Mage::getSingleton('core/design_package')->getTheme('skin') . '<br />' ?>
</div>

<?php /*$_productCollection = Mage::getModel('catalog/product')
    ->getCollection()
    ->addAttributeToSort('created_at', 'DESC')
    ->addAttributeToSelect('*')
    ->load();
*/?>
<?php
    $category = Mage::getModel('catalog/category')->load(6); //->load($categoryId);

    $_productCollection = $category->getProductCollection()
    ->joinField('category_id', 'catalog/category_product', 'category_id', 'product_id = entity_id', null, 'left')
    ->addAttributeToFilter('category_id', array('in' => array(1 ,2 ,3)))
    //->addAttributeToSelect(array('name', 'price'));
    ->addAttributeToSelect('*');
    ?>

<div class="block-image-slider">
    <div class="block-title">
        <h2><?php echo $this->getTitle() ?></h2>
    </div>
    <div class="productslider-container">
        <div id="productslider-<?php echo $this->getCategoryId() ?>">
            <?php foreach ($_productCollection as $_product): ?>
                <?php /*print_r($_product); */ ?>
                <div class="slider-item">
                    <a href="<?php echo $_product->getProductUrl() ?>"
                       title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                       class="carousel-image">
                        <img    src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250); ?>"
                                width="210" height="210"
                                alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                    </a>
                    <div class="slider-item-content">
                        <p>
                            <?php echo $_product->getName() ?>
                        </p>
                        <?php echo $this->getPriceHtml($_product) ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>

        <h1>separator div class="productslider-controls</h1>
        <div class="productslider-controls">
            <a id="btn-prev-<?php echo $this->getCategoryId() ?>" class="btn-prev" href="#">&lt;</a>
            <a id="btn-next-<?php echo $this->getCategoryId() ?>" class="btn-next" href="#">&gt;</a>
            <div id="pager-<?php echo $this->getCategoryId() ?>" class="pager"></div>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function () {
        jQuery("#productslider-<?php echo $this->getCategoryId() ?>").carouFredSel({
            width: "variable",
            //width: '100%',
            //direction: "right",
            //responsive: false,
            items: 4,
            prev: '#btn-prev-<?php echo $this->getCategoryId() ?>',
            next: '#btn-next-<?php echo $this->getCategoryId() ?>',
            pagination: '#pager-<?php echo $this->getCategoryId() ?>'
        });
    });
</script>