<div class="container">
    <div class="row">
        <?php $_productCollection=$this->getLoadedProductCollection() ?>
        <?php if(!$_productCollection->count()): ?>
            <div class="note-msg">
                <?php echo $this->__('There are no products matching the selection.') ?>
            </div>
        <?php else: ?>

        <?php // Grid Mode ?>
        <div class="what-we-build-home fadeInUp wow animated" style="margin-bottom:45px;">
            <h2 class="text-center">Featured Products</h2>
            <?php $_collectionSize=$_productCollection->count() ?>
            <?php $i=0; foreach ($_productCollection as $_product): ?>
                <?php if($i++%7==0): ?>
                    <div class="list_carousel responsive">
                    <ul id="featProdCar">
                <?php endif ?>
                <li>
                    <br />
                    <div id="featured-product" class="tab<?php echo $i ?>">
                        <div class="featured-product-body">

                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                                <center>
                                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(180, 180); ?>" width="180" height="180" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                            </a>
                            </center>
                            <h3><?php echo $this->htmlEscape($_product->getName()) ?><?php echo $this->getPriceHtml($_product, true) ?></h3>
                            <!--get short description of products----<p><?php //echo $this->htmlEscape($_product->getShortDescription()) ?></p>-->

                            <p style="border:1px solid ">
                                <?php echo $_product->getDescription() ?></p>

                        </div>

                        <div class="clearfix" />
                    </div>
                    <?php if ($i%7==0 && $i!=$_collectionSize): ?>
                    <?php endif ?>

                </div>
                </li>

            <?php endforeach ?>
            </ul>

            <script type="text/javascript">
                decorateGeneric($$('.grid-row'), ['last', 'odd', 'even']);
            </script>
            <?php endif; ?>

        </div>

    </div>
</div>
</div>
